# preParflow.sub
# 2016.01 Carolyn Voter
# Submit script to convert *.sa input files to *.pfb

#-------------------------------------------------------------------------------
# ***Run-specific arguments***
# "runname" must come from DAG
#-------------------------------------------------------------------------------
universe = vanilla
executable = /home/cvoter/Parflow/models/scripts/preParflow.sh
arguments = $(runname)
output = prePF.out
error = prePF.err
log = prePF.log

request_cpus = 1
request_memory = 1MB
request_disk = 5MB
requirements = ( HasGluster == true ) && (OpSysMajorVer == 7)

initialdir = /home/cvoter/Parflow/models/$(runname)
transfer_input_files = /home/cvoter/Parflow/models/scripts/preParflow.tcl,\
transfer_input_files = /home/cvoter/Parflow/models/scripts/runParflow.tcl
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

queue
